DefaultTerms:
  - InternalCode: '3d0d1df1-e8a7-45bb-abf4-63b4ecdbc2ea'
    Name: 'BG_MartDimension_Identity'
    NamingConvention: '{{ModelObject.Name}}_ID'
  - InternalCode: '618f7171-3c96-4093-9f01-05b68d3ee3f1'
    Name: 'BG_MartFact_ForeignKey_Identity'
    NamingConvention: '{{ReferencedModelObject.Name}}_{{Role}}_ID'
