name: 'Product Launch Event'
description: 'product-launch-event'
id: 'f4af988b-6568-4aee-2bb3-08db50014549'
configuration:
  id: 'biGENIUS.Implementation.Generator.VaultAndMart.Mssql'
  version: '1.6.1'
sourceSystems:
  - id: 'cbdf229a-4dce-47e1-81a5-71e4bee0edb5'
    name: 'Blackforest Markets'
    description: 'Retail Chain'
    sourceSystemTypeId: 'f69491d8-eed8-43a0-89f9-60195b3415c2'
    activeDiscovery: 'e429f304-672e-41d0-b83e-66425f9b4692'
version: 'v1.4'
propertyValues: []
