name: Product Launch Event
description: product-launch-event
id: f4af988b-6568-4aee-2bb3-08db50014549
configuration:
  id: biGENIUS.Implementation.Generator.VaultAndMart.Mssql
  version: 1.0.0
views:
  - id: 2edf46ca-c8ac-45eb-833e-a54ed53c325f
    name: Datamodel View 1
    description: Default view for data model.
    type: data-model
    default: true
  - id: edfe9c89-57e1-4f41-a8c1-d53b6de09472
    name: Sales Information ERP
    description: ERP Sales Information
    type: data-pipe
    default: true
  - id: 2142fb6b-b215-4238-b0e5-4bd90041a867
    name: Sales Information POS
    description: Sales Information POS
    type: data-pipe
    default: false
sourceSystems:
  - name: erp
    description: ERP
    id: 963df8c5-e464-4584-83f8-ff3734e75456
  - name: POS
    description: POS
    id: a86540c3-707b-4e4a-b19f-2317c01d045b
version: v1
